name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for deploy-pages
  pages: write # Allows GitHub Pages deployment
  contents: read # Required for accessing repo content

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static # Ensure this matches your Storybook output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
